# Generated by Django 3.2.18 on 2023-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(help_text='Content of the comment', max_length=140, verbose_name='내용'),
        ),
    ]
